# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_items', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('_bonus_amount', models.IntegerField()),
                ('ability_bonus', models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')], default=None)),
                ('save_bonus', models.IntegerField(choices=[(0, 'Fortitude'), (1, 'Reflex'), (2, 'Will')], default=None)),
                ('from_x_stat', models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')], default=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_effect', to='main.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('W', 'Weapon'), ('A', 'Armor'), ('S', 'Shield'), ('C', 'Clothing'), ('T', 'Tool')], default='T', max_length=1)),
                ('damage', models.CharField(max_length=50)),
                ('critical', models.CharField(max_length=50)),
                ('weapon_range', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('damage_type', models.CharField(max_length=50)),
                ('base_ac_bonus', models.IntegerField(max_length=50)),
                ('base_acp', models.CharField(max_length=50)),
                ('base_asf', models.CharField(max_length=50)),
                ('weapon_enhancement_bonus', models.CharField(max_length=50)),
                ('armor_enhancement_bonus', models.CharField(max_length=50)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
        ),
        migrations.CreateModel(
            name='RacialAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('char_name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('alignment', models.CharField(max_length=200)),
                ('deity', models.CharField(max_length=200)),
                ('campaign', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('_size', models.CharField(max_length=200)),
                ('disp_base_str', models.CharField(max_length=5)),
                ('disp_base_dex', models.CharField(max_length=5)),
                ('disp_base_con', models.CharField(max_length=5)),
                ('disp_base_int', models.CharField(max_length=5)),
                ('disp_base_wis', models.CharField(max_length=5)),
                ('disp_base_cha', models.CharField(max_length=5)),
                ('disp_base_will', models.CharField(max_length=5)),
                ('disp_base_ref', models.CharField(max_length=5)),
                ('disp_base_fort', models.CharField(max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_stat', models.IntegerField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='main.Sheet')),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='sheets',
            field=models.ManyToManyField(related_name='effect', to='main.Sheet'),
        ),
        migrations.AddField(
            model_name='effect',
            name='skill_bonus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Skill'),
        ),
        migrations.AddField(
            model_name='classability',
            name='effect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Effect'),
        ),
    ]
