# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='acp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='misc_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='ranks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='rename',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='stat_override',
            field=models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='super_skill',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='default_stat',
            field=models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sheet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Sheet'),
        ),
    ]
