# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160516_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect',
            old_name='_bonus_amount',
            new_name='bonus_amount',
        ),
        migrations.AddField(
            model_name='effect',
            name='bonus_type',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
