# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160517_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='ability_bonus',
            field=models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='from_x_stat',
            field=models.IntegerField(choices=[(0, 'Strength'), (1, 'Dexterity'), (2, 'Constitution'), (3, 'Intelligence'), (4, 'Wisdom'), (5, 'Charisma')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='save_bonus',
            field=models.IntegerField(choices=[(0, 'Fortitude'), (1, 'Reflex'), (2, 'Will')], default=None, null=True),
        ),
    ]
